apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
  namespace: qa
  labels:
    app: nodejs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: mycntr
        image: 020567785666.dkr.ecr.ap-south-1.amazonaws.comnodejs:25
        imagePullPolicy: Always
        ports:
         -   containerPort: 3000
      imagePullSecrets:
          - name: awsecr

